version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    reviewers:
      - a01sa01to
    groups:
      root:
        patterns:
          - '@jest/*'
          - '@types/*'
          - 'jest'
          - 'ts-jest'
          - 'typescript'
          - 'ts-node'
      textlint:
        patterns:
          - 'textlint-*'
          - '@textlint/*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@typescript-eslint/*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    reviewers:
      - a01sa01to
